ChronoBank/ChronoMint

- app/index.html
- app/javascripts/app.js
- app/stylesheets/app.css
- contracts/ConvertLib.sol
- contracts/MetaCoin.sol
- contracts/Migrations.sol
- migrations/1_initial_migration.js
- migrations/2_deploy_contracts.js
- test/metacoin.js
- truffle.js
I literally just ran "truffle init" and committed... 
No testing required.
> generate truffle boilerplate

- .travis.yml
- package.json
I've added coveralls.io service integration
> coveralls.io support in travis-ci

- setup/4_setup_assets.js
- src/components/forms/IssueLH/IssueLHForm.js
- src/components/modals/RewardsEnablingModal.js
- src/components/pages/WalletPage/BalancesWidget/TimeBalanceWidget.js
- src/components/pages/WalletPage/SendWidget.js
- src/components/pages/votingPage/Polls.js
- src/components/pages/votingPage/VotingDepositModal.js
- src/components/pages/votingPage/index.js
- src/components/pages/votingPage/statusBlocks.js
- src/dao/VoteDAO.js
- src/models/Operation.js
- src/models/PollModel.js
- src/redux/polls/data.js
- src/redux/polls/polls.js
- src/redux/wallet/wallet.js
Add ActivatePoll button
Wallet balance fix
> Add ActivatePoll button & fixes

- package.json
- specs/redux/session/actions.spec.js
- src/redux/configureStore.js
- src/redux/session/actions.js
Also:
fix npm version issue with history dependencies;
add redux devTools, remove logger;
> MINT-109 fix always empty profile after refresh

- specs/redux/session/actions.spec.js
- specs/redux/watcher.spec.js
- src/components/layout/LeftDrawer/NavigationMenu.js
- src/pages/ProfilePage.js
- src/redux/session/actions.js
- src/redux/watcher.js
- src/router.js
Move the CBE resources in the subdomain /cbe
Change relevant links on /cbe/...
Checking the access rights on the CBE resources and redirecting to the /wallet without access rights
Remove redirection for non-CBE users on reloading non-CBE resources
MINT-76 fix duplicated notifications
> MINT-108 /cbe/ routes; MINT-76 duplicated watch calls fix

- .eslintrc
- package.json
- setup/4_setup_assets.js
- specs/init.js
- src/components/common/IPFSFileSelect.js
- src/components/layout/LeftDrawer/UserInfo.js
- src/components/modals/IPFSFileUpload.js
- src/components/pages/SettingsPage/CBEAddresses.js
- src/components/pages/SettingsPage/OtherContracts.js
- src/dao/AbstractContractDAO.js
- src/dao/LOCDAO.js
- src/dao/LOCsManagerDAO.js
- src/dao/OrbitDAO.js
- src/dao/UserDAO.js
frontend part
fix specs
remove node deprecated-api
add `npm run reset` for reset all contracts
add `npm run retest` for reset contracts & run tests
> MINT-132 orbit hash bytes32+bytes14 to bytes32; MINT-137 Implement blockchain reverter to specs

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- src/components/layout/LeftDrawer/UserInfo.js
- src/components/modals/DepositTimeModal.js
- src/components/modals/SendToExchangeModal.js
- src/components/pages/votingPage/Polls.js
fix svg issue
remove possibility horizontal scroll for user profile area
fix code style
> MINT-146 Left drawer layout

- src/layouts/partials/ExchangeContent.scss
> MINT-395 Fix Exchange page markup

- src/layouts/Splash/Splash.js
- src/layouts/partials/InfoPartial.scss
- src/layouts/partials/WalletContent.jsx
- src/pages/lib/DashboardPage.jsx
- src/pages/lib/ExchangePage.jsx
- src/pages/lib/OperationsPage.jsx
- src/pages/lib/RewardsPage.jsx
- src/pages/lib/SettingsPage.jsx
- src/pages/lib/VotingPage.jsx
- src/pages/lib/WalletPage.jsx
This changes makes look and feel of the app more 'mobile' on mobile devices.
> MINT-448 Modify webview mode layout

- src/components/dashboard/Poll.jsx
- src/components/dialogs/VoteDialog.jsx
- src/dao/AbstractContractDAO.js
- src/dao/ContractsManagerDAO.js
- src/layouts/partials/VotingContent.jsx
- src/layouts/partials/WalletContent.jsx
(cherry picked from commit 72049b9)
> MINT-476 Wrong response from getMemberVotesForPoll method, MINT-477 Redirect on login page on Vote action

- ws-server.js
> fix HTTP request

- src/components/common/IPFSImage/IPFSImage.jsx
https://chronobank.atlassian.net/browse/MINT-653
> Fix show icon logic

- src/components/common/HashedIcon/TokenIcon.js
- src/components/common/HashedIcon/UserIcon.js
- src/components/common/HashedIcon/utils.js
- src/components/dialogs/AddTokenDialog.jsx
- src/components/forms/EditManagersBaseForm/EditManagersBaseForm.js
- src/components/forms/EditManagersBaseForm/EditManagersBaseForm.scss
- src/components/forms/EditManagersBaseForm/ManagerItem.js
- src/layouts/Markup.jsx
- src/router.js
https://chronobank.atlassian.net/browse/MINT-632
> MINT-632 Implement UserIcon with hash function

- scripts/start.js
- src/Login/components/LoginLocal/LoginLocal.js
- src/Login/network/settings.js
- src/Login/redux/network/actions.js
- src/components/assetsManager/PlatformInfo/lang.js
- src/components/assetsManager/PlatformsList/PlatformsList.jsx
- src/models/TokenModel.js
- src/redux/assetsManager/actions.js
Fix asset create, fix login with local testrpc, other small fixes.
> MINT-804 hotfix: can't create token

- packages/login/network/ExchangeProvider.js
- packages/login/network/settings.js
- src/pages/LoginPage/LoginPage.js
Added middleware links map and auto link
> MINT-865 Add automatic link url to Middleware

- src/components/assetsManager/AddTokenDialog/AddTokenForm.jsx
- src/components/exchange/AddExchangeDialog/AddExchangeForm.scss
- src/components/exchange/AddExchangeDialog/TokenListSelector.jsx
- src/dao/ERC20ManagerDAO.js
- src/layouts/partials/HeaderPartial/HeaderPartial.jsx
Added transform to upper case and some other fixes
> MINT-871 Add transformer to uppercase in add token functionality

- src/components/dashboard/DepositTokens/DepositTokensForm.jsx
- src/components/dashboard/SendTokens/SendTokensForm.jsx
Added auto-select first of tokens list and sort tokens list
> MINT-912 hotfix: Auto-select firs token in sendTokens components

- src/components/exchange/AddExchangeDialog/TokenListSelector.jsx
> MINT-926 Fix error in AddExchangeFrom

- packages/login/network/ExchangeProvider.js
- src/components/assetsManager/PlatformsList/PlatformsList.jsx
- src/components/assetsManager/PlatformsList/PlatformsList.scss
- src/components/exchange/AddExchangeDialog/TokenListSelector.jsx
- src/components/exchange/BuyTokensDialog/validate.js
- src/dao/ERC20ManagerDAO.js
- src/dao/ExchangeManagerDAO.js
- src/layouts/partials/InfoPartial/InfoPartial.jsx
- src/models/tokens/TokenModel.js
- src/redux/exchange/actions.js
- src/redux/exchange/reducer.js
- src/redux/mainWallet/actions.js
> MINT-940 Test app on stage after tests merge

- src/components/dashboard/IconSection/IconSection.jsx
- src/components/dashboard/IconSection/IconSection.scss
fix TODO and change border-radius to 2px
> MINT-426 Set border radius 2px

- src/components/dashboard/SendTokens/SendTokensForm.jsx
- src/components/dashboard/SendTokens/SendTokensForm.scss
- src/dao/EthereumDAO.js
- src/i18n/en.js
- src/i18n/ru.js
- src/layouts/partials/DashboardContent/DashboardContent.scss
- src/redux/tokens/actions.js
- src/utils/Web3Converter.js
add 'Gas price' slider to send token
and fix in render
> MINT-549 add gasPrice slider

- packages/login/network/BitcoinAbstractNode.js
- packages/login/network/BitcoinBlockexplorerNode.js
- src/components/dashboard/TransactionsTable/TransactionsTable.jsx
- src/dao/BitcoinDAO.js
- src/models/wallet/TransactionsCollection.js
- src/redux/mainWallet/actions.js
Add getting for btc-like tokens and small fixes
> MINT-910 Load tx history for BTC-like tokens (only for BlockexplorerNode)

- src/components/dashboard/DepositTokens/DepositTokensForm.jsx
> MINT-1007 Hotfix: deposit time

- src/components/dashboard/DepositTokens/DepositTokensForm.jsx
- src/components/dashboard/DepositTokens/validate.js
> MINT-999 Deposit button in the DepositeToken widget should be locked if the current value of a Deposit is 0 and the Amount value is 0

- src/components/dashboard/Poll/Poll.jsx
- src/components/dashboard/Poll/Poll.scss
- src/components/dialogs/PollDetailsDialog.jsx
- src/components/dialogs/PollDetailsDialog.scss
- src/components/dialogs/VoteDialog.jsx
- src/components/dialogs/VoteDialog.scss
- src/components/dialogs/poll/PollEditDialog/PollEditForm.jsx
- src/dao/PollEmitterDAO.js
- src/dao/PollInterfaceDAO.js
- src/dao/VotingManagerDAO.js
- src/i18n/en.js
- src/i18n/ru.js
- src/models/PollDetailsModel.js
- src/redux/voting/actions.js
Fixed comments and some changes
> MINT-1017 Final Voting tests on testrpc after killPoll PR will be merged & RC branch of the contracts will be published

- src/components/operations/Operations.jsx
> MINT-1039 Errors in natvigation on CBE pages

- src/components/dialogs/tokens/AddCurrencyDialog.jsx
- src/components/dialogs/tokens/TokenRow.jsx
- src/dao/ERC20ManagerDAO.js
- src/layouts/partials/InfoPartial/InfoPartial.jsx
- src/models/ProfileModel.js
- src/redux/session/actions.js
- src/redux/session/selectors.js
add field `version` to profile object.
add support for old profiles scheme
> MINT-1037 fix profile scheme

- src/dao/AbstractContractDAO.js
> MINT-1076 bad notifications dropdown after tx cancellation

- .travis.yml
- package.json
> MD-163 Auto deploy for the mint.chronobank.io

- src/components/dialogs/LOC/LOCDialog/LOCDialog.js
- src/components/dialogs/LOC/LOCDialog/LOCForm.js
- src/components/dialogs/LOC/LOCIssueDialog/LOCIssueDialog.js
- src/components/dialogs/LOC/LOCIssueDialog/LOCIssueForm.js
- src/components/dialogs/LOC/LOCRedeemDialog/LOCRedeemDialog.js
- src/components/dialogs/LOC/LOCRedeemDialog/LOCRedeemForm.js
- src/components/dialogs/LOC/LOCSendToExchangeDialog/SendToExchangeDialog.js
- src/components/dialogs/LOC/LOCSendToExchangeDialog/SendToExchangeForm.js
- src/components/dialogs/LOC/LOCSendToExchangeDialog/validate.js
- src/components/locs/LOCItem/LOCItem.scss
- src/components/locs/LOCItem/LOCItemButtons.js
- src/components/locs/PageTitle.js
- src/dao/LHTDAO.js
- src/dao/LOCManagerDAO.js
- src/models/LOCModel.js
- src/redux/locs/actions.js
- src/redux/locs/selectors.js
> MINT-1105 Fix Send to exchange on the LOCs page

- src/components/dashboard/Poll/Poll.scss
- src/components/dialogs/PollDetailsDialog.scss
- src/components/dialogs/poll/PollEditDialog/PollEditForm.jsx
- src/components/dialogs/poll/PollEditDialog/PollEditForm.scss
- src/dao/PollInterfaceDAO.js
- src/dao/VotingManagerDAO.js
- src/models/voting/VotingMainModel.js
- src/redux/voting/actions.js
- src/redux/voting/reducer.js
Implement layout for slider.
Some changes.
> MINT-1121 Use slider for the voteLimit field on the "New Poll" dialog

- src/dao/PollInterfaceDAO.js
- src/dao/VotingManagerDAO.js
MINT-1129 ipfs higher await interval
MINT-1130 EndPoll fails with Out of gas on the Mainnet
> MINT-1129 ipfs + MINT-1130 EndPoll

- src/components/common/GasSlider/GasSlider.jsx
- src/components/common/GasSlider/lang.js
- src/components/dashboard/SendTokens/SendTokens.jsx
- src/components/dashboard/SendTokens/SendTokensForm.jsx
- src/components/dialogs/ConfirmTxDialog/ConfirmTxDialog.js
- src/components/dialogs/ConfirmTxDialog/ConfirmTxDialog.scss
- src/dao/AbstractContractDAO.js
- src/dao/EthereumDAO.js
- src/redux/session/selectors.js
- src/redux/ui/actions.js
- src/redux/watcher/actions.js
Implement slider component and created styles
> MINT-1055 Implement gas slider on the ConfirmTxDialog

- packages/login/redux/network/actions.js
- src/dao/ERC20ManagerDAO.js
- src/layouts/partials/ProfileSidePanel/ProfileSidePanel.scss
added BTG to the ProfilePartial tokens list
> added BTG to the ProfilePartial tokens list

- src/layouts/partials/ProfileSidePanel/ProfileSidePanel.jsx
- src/redux/session/selectors.js
Clean tokens without address in profile panel
> Clean tokens without address in profile panel

- src/i18n/en.js
- src/i18n/ru.js
- src/layouts/partials/WalletContent/WalletContent.jsx
- src/layouts/partials/WalletContent/lang.js
Remove lang phrase and limit layout.
> MINT-1089 Remove notification (and a limitation of exists) on the Deposit time widget on the Mainnet

- src/components/common/SideStack/SideStack.jsx
- src/layouts/partials/SidePanel/SidePanel.jsx
- src/redux/sides/actions.js
- src/redux/sides/actions.spec.js
- src/redux/sides/reducer.js
- src/redux/sides/reducer.spec.js
> Added animation for ProfileSide panel & precision to TokenValue. Fixes

- src/components/assetsManager/AssetManager/AssetManager.jsx
- src/components/assetsManager/AssetManager/lang.js
Change title for Add new platform button
> Change title for Add new platform button

- package.json
- packages/login-ui/components/LoginWithOptions/lang.js
- packages/login/network/NemEngine.js
- packages/login/network/NemProvider.js
- src/dao/ERC20ManagerDAO.js
+ MINT-1224 Implement ability to calculate fee without signing tx for NEM
> MINT-1230 Pre-release updates

- src/components/operations/Operations.jsx
- src/dao/AbstractMultisigContractDAO.js
- src/dao/AssetsManagerDAO.js
- src/dao/PendingManagerDAO.js
- src/models/OperationModel.js
- src/redux/operations/actions.js
- src/redux/operations/reducer.js
Fix pending operations confirm.
> MINT-1347 Change attach platform action.

- packages/login/network/EthereumMiddlewareNode.js
- packages/login/network/EthereumNode.js
Added right urls for Middleware.
> MINT-1348 Discuss and fix events from Middleware

- packages/login/network/AbstractNode.js
Added info about server URL into trace log
> Improved trace readability

- packages/login/network/BitcoinBlockexplorerNode.js
- packages/login/network/BitcoinMiddlewareNode.js
- packages/login/network/BitcoinProvider.js
- packages/login/network/NemMiddlewareNode.js
- packages/login/network/NemProvider.js
- src/dao/BitcoinDAO.js
- src/dao/NemDAO.js
Also enhanced trace messages (added module names)
> Error Handling improvement: catch and trace HTTP errors 502 from ChronoBank middlewares

- packages/login/network/BitcoinEngine.js
- packages/login/network/EthereumEngine.js
- packages/login/network/mnemonicProvider.js
- packages/login/network/privateKeyProvider.js
- src/redux/mainWallet/actions.js
> MINT-1595 Fix addresses on login with mnemonic and wallet file

- packages/core/redux/tokens/actions.js
error: bundling failed: TypeError: /Users/alexo/projects/ChronoMint-RN/node_modules/@chronobank/core/redux/tokens/actions.js: Duplicate declaration "e"
> Fix build error: Duplicate declaration "e"

- packages/login-ui/package.json
- packages/login/network/NetworkService.js
- src/app.js
- yarn.lock
Fix dependencies.
Update yarn.lock
> MINT-1640 prepare release

- src/components/common/TopButtons/buttons.js
- src/i18n/en.js
- src/layouts/partials/PollContent/PollContent.jsx
- src/layouts/partials/PollContent/PollContent.scss
- src/layouts/partials/PollContent/lang.js
- src/layouts/partials/VoteHistoryContent/VoteHistoryContent.jsx
- src/layouts/partials/VoteHistoryContent/VoteHistoryContent.scss
- src/layouts/partials/VoteHistoryContent/lang.js
- src/layouts/partials/index.js
- src/layouts/partials/lang.js
- src/pages/lib/VoteHistoryPage.jsx
- src/pages/lib/index.js
- src/router.js
Implemented layout for poll history page.
> [WIP] MINT-1644 Implement page "poll-changes"

- src/layouts/partials/index.js
- src/pages/lib/AddWalletPage.jsx
- src/pages/lib/AssetsPage.jsx
- src/pages/lib/DepositPage.jsx
- src/pages/lib/DepositsPage.jsx
- src/pages/lib/ExchangePage.jsx
- src/pages/lib/LOCPage.jsx
- src/pages/lib/NewPollPage.jsx
- src/pages/lib/OperationsPage.jsx
- src/pages/lib/PollPage.jsx
- src/pages/lib/RewardsPage.jsx
- src/pages/lib/SettingsPage.jsx
- src/pages/lib/TwoFAPage.jsx
- src/pages/lib/VoteHistoryPage.jsx
- src/pages/lib/VotingPage.jsx
- src/pages/lib/WalletPage.jsx
- src/pages/lib/WalletsPage.jsx
> [1] CM-93: resolved 69 circular dependencies

- package.json
- packages/login/network/BitcoinNode.js
- packages/login/network/EthereumNode.js
Increase timeout because send request is taken about 6 seconds.
> MINT-1784 Unknown error during BTC Send transaction on production server

- package.json
- packages/login/network/BitcoinNode.js
- packages/login/network/EthereumNode.js
Merge pull request #782 from wAISw/MINT-1784-Unknown-error-during-BTC-Send-transaction-on-production-server
MINT-1784 Unknown error during BTC Send transaction on production server
> Release 0.9.7

- packages/core/dao/NemDAO.js
- yarn.lock
> MINT-1919 XMIN balance is the same as XEM

- src/components/common/TheCookies/TheCookies.jsx
- src/components/common/TheCookies/TheCookies.scss
- src/components/common/TheCookies/lang.js
- src/components/lang.js
- src/layouts/Markup.jsx
- src/layouts/Splash/Splash.js
- src/redux/ui/actions.js
- src/redux/ui/constants.js
- src/redux/ui/reducer.js
- src/redux/ui/selectors.js
- src/redux/ui/thunks.js
- yarn.lock
Added notification about cookie.
> MINT-1853 Cookies

- index-presentation.html
- index.html
Added google analytics code in templates.
> MINT-1860 To integrate App with Google Analytics

- Dockerfile
> Attempt to fix deployment to host
